### ISSUE TITLE
install failed checksum mismatch

### ISSUE THREAD

**Issue by caketi** [hiddengearz/jsubfinder#1]
go get -u github.com/hiddengearz/jsubfinder
go get: github.com/hiddengearz/jsubfinder@none updating to
        github.com/hiddengearz/jsubfinder@v0.0.0-20201017010009-cef78df1c388 requires
        github.com/projectdiscovery/httpx@v1.0.2: verifying go.mod: checksum mismatch
        downloaded: h1:N3YfUNqeDuVgHdHawzOiwepuPBP5KexlL7CwQqDif6M=
        sum.golang.org: h1:OwvMc5ogx69xukKXY6kIrDP6dgOYr4VtEWyr6o573Xs=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

**Comment by hiddengearz** [comment]
Unable to reproduce, is anyone else having this issue?
